---

- name: Update apt cache.
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400 #One day
    dpkg_options: 'force-confdef,force-confold'
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Install common packages
  apt:
    name: "{{ common_pkgs }}"
    state: latest

- name: Ensure default web group exists
  group:
    name: "{{ web_group | default('www-data') }}"
    state: present

- name: Ensure default web user exists
  user:
    comment: "{{ web_user | default('www-data') }}"
    name: "{{ web_user | default('www-data') }}"
    group: "{{ web_group | default('www-data') }}"
#    shell: /sbin/nologin
    home: "{{ web_home | default('/var/www') }}"
