---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Install required dependencies.
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ common_pkgs }}"

- name: Install imagemagick
  yum:
    name: ImageMagick
    state: installed
